### ISSUE TITLE
Can't handle period character in json field names

### ISSUE THREAD

**Issue by snikch** [verdverm/frisby#7]
Hey - first up, thanks for the work on your library. We're evaluating using it and Iv'e come across an issue with the `ExpectJson` api.

I have a json response that looks like this:

```json
{
  "error": "Invalid data supplied",
  "fields": {
    "display_name": "display_name is required",
    "ends_at": "ends_at is required",
    "starts_at": "starts_at is required",
    "state.state": "state must be one of the following: \"active\", \"inactive\""
  }
}
```

I'd love to be able to test this via `ExpectJson("fields.state.state", "xxx")` but for obvious reasons this isn't possible.

I see two options for fixing this. One is to change the signature of the current api, which would be a backwards incompatible change: `ExpectJson(expectation string, path string...)`. The other option would be to add a new method with that signature, e.g. `ExpectJsonAtPath(expecation string, path string...)`.

Thoughts?

**Comment by verdverm** [comment]
How about adding a feature to parameterize the separation token ?

like: `response~field~state.state`

That would make frisby much more flexible and stay backwards compatible too

**Comment by snikch** [comment]
Sounds good. I can do a PR for this when I'm next in the code.

**Comment by verdverm** [comment]
awesome, thanks!

**Comment by verdverm** [comment]
I would add a field and setter function in global.go with the default being `'.'`

Then use the global field every where like `split(path,Golbal.path_separator)`

**Comment by verdverm** [comment]
Global PathSeparater added by #9
