### ISSUE TITLE
Can't run expectation against array index values

### ISSUE THREAD

**Issue by snikch** [verdverm/frisby#8]
I can't seem to find a way to do `ExpectJson` with a path like `payload[0].state` or `payload.[0].state`, and based on the code i don't think it's supported.

Do you think it would be possible to update the way that paths are looked up from `simp_json.GetPath` to a loop that evaluates each of the keys and checks to see if there's is an index lookup in it?

Currently we have:
```go
path_items := strings.Split(path, ".")
simp_json = simp_json.GetPath(path_items...)
```

We could look at something like (exclude the psuedo code, I haven't tested this):

```go
for _, pathItem := range strings.Split(path, ".") {
	matches := regexp.MustCompile("^\\[([0-9]+)\\]$").FindStringSubmatch(pathItem)
	if len(matches) < 2 {
		simp_json = simp_json.Get(pathItem)
	} else {
		index, _ := strconv.Atoi(matches[1])
		simp_json = simp_json.GetIndex(index)
 	}
}
```

**Comment by verdverm** [comment]
Your suggestion seems reasonable, 2 level splitting

Does something like `payload.0.state` work?

I would prefer to see this as a PR agains https://godoc.org/github.com/bitly/go-simplejson#Json.GetPath

(since frisby is just wrapping the simplejson.GetPath call)

**Comment by snikch** [comment]
`payload.0.state` crossed my mind but we'd need to be careful to avoid the inverse problem of not being able to address this valid structure:

```json
{
  "payload": {
    "0": {
      "state": "test"
    }
  }
}
```

Using `[0]` felt more specific and less likely to collide, but it might be ok to just use `0` along with a check if the element is an array.

Correct on making this an issue for the upstream. Will look into it 👌

**Comment by verdverm** [comment]
+1 for the `payload.array.[0].field` syntax then

**Comment by verdverm** [comment]
Non-bracket array indexing added by #10
